@startuml

[*] -> ログイン
ログイン --> チュートリアル:初回ログイン
ログイン --> ログイン後:2回目以降のログイン
チュートリアル --> ログイン後:チュートリアル閲覧完了後

state ログイン後 {
  ログイン後 --> ログイン:ログアウトをクリック
  [*] --> タイムライン
  state タイムライン{
    [*] --> タイムライン一覧
    タイムライン --> 検索:検索をクリック
    タイムライン --> 登録:登録をクリック
    タイムライン --> タグ編集:タグ編集をクリック
    タイムライン --> 設定:設定をクリック
    タイムライン一覧 --> 詳細:カードをクリック
  }

  state 検索{
    [*] --> 検索条件
    検索 --> タイムライン:タイムラインをクリック
    検索条件 --> 検索結果:検索を実行
    検索結果 --> 検索条件:戻る
    検索結果 --> 詳細:カードをクリック
  }
  state 詳細{
    [*] --> 詳細表示
    詳細 --> タイムライン:戻る
    詳細 --> 検索:戻る
    詳細表示 --> 編集:編集アイコンをクリック
    編集 --> 詳細表示:編集を完了
  }
  state 登録{
    登録 -> タイムライン:タイムラインをクリック/登録完了
  }
  state タグ編集{
    タグ編集 -> タイムライン:タイムラインをクリック
  }
  state 設定{
    設定 -> タイムライン:タイムラインをクリック
  }
}

@enduml
